from PyQt5 import QtCore, QtGui, QtWidgets
from City import *


class Ui_Forecast(object):
    def setupUi(self, Forecast, city: City):
        Forecast.setObjectName("Forecast")
        Forecast.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(Forecast)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 50, 40, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 50, 40, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 50, 40, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 50, 40, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 50, 40, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(150, 90, 31, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(270, 90, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(330, 90, 31, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(90, 90, 31, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(210, 90, 31, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(150, 130, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(270, 130, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(330, 130, 31, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(90, 130, 31, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(210, 130, 31, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(150, 170, 31, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(270, 170, 31, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(330, 170, 31, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(90, 170, 31, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(210, 170, 31, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(30, 90, 31, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(30, 130, 41, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(30, 170, 51, 16))
        self.label_24.setObjectName("label_24")
        Forecast.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Forecast)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        Forecast.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Forecast)
        self.statusbar.setObjectName("statusbar")
        Forecast.setStatusBar(self.statusbar)

        self.retranslateUi(Forecast, city)
        QtCore.QMetaObject.connectSlotsByName(Forecast)

    @staticmethod
    def get_forecaste_info(city: City):
        days = list()
        o3 = list()
        pm10 = list()
        pm25 = list()
        for i in range(5):
            days.append(str(city.forecast["o3"][i]["day"][5:]))
            o3.append(str(city.forecast["o3"][i]["avg"]))
            pm10.append(str(city.forecast["pm10"][i]["avg"]))
            pm25.append(str(city.forecast["pm25"][i]["avg"]))
        return days, o3, pm10, pm25

    def retranslateUi(self, Forecast, city: City):
        # getting forecast data
        days, o3, pm10, pm25 = self.get_forecaste_info(city)

        _translate = QtCore.QCoreApplication.translate
        Forecast.setWindowTitle(_translate("Forecast", city.name))
        self.label.setText(_translate("Forecast", "Average Forecast for five days"))
        self.label_2.setText(_translate("Forecast", days[0]))
        self.label_3.setText(_translate("Forecast", days[1]))
        self.label_4.setText(_translate("Forecast", days[2]))
        self.label_5.setText(_translate("Forecast", days[3]))
        self.label_6.setText(_translate("Forecast", days[4]))
        self.label_7.setText(_translate("Forecast", o3[1]))
        self.label_8.setText(_translate("Forecast", o3[3]))
        self.label_9.setText(_translate("Forecast", o3[4]))
        self.label_10.setText(_translate("Forecast", o3[0]))
        self.label_11.setText(_translate("Forecast", o3[2]))
        self.label_12.setText(_translate("Forecast", pm10[1]))
        self.label_13.setText(_translate("Forecast", pm10[3]))
        self.label_14.setText(_translate("Forecast", pm10[4]))
        self.label_15.setText(_translate("Forecast", pm10[0]))
        self.label_16.setText(_translate("Forecast", pm10[2]))
        self.label_17.setText(_translate("Forecast", pm25[1]))
        self.label_18.setText(_translate("Forecast", pm25[3]))
        self.label_19.setText(_translate("Forecast", pm25[4]))
        self.label_20.setText(_translate("Forecast", pm25[0]))
        self.label_21.setText(_translate("Forecast", pm25[2]))
        self.label_22.setText(_translate("Forecast", "O3:"))
        self.label_23.setText(_translate("Forecast", "PM10:"))
        self.label_24.setText(_translate("Forecast", "PM2.5:"))
