from PyQt5 import QtCore, QtGui, QtWidgets
from City import *


class Ui_RealTime(object):
    def setupUi(self, RealTime, city: City):
        RealTime.setObjectName("RealTime")
        RealTime.resize(300, 300)
        self.centralwidget = QtWidgets.QWidget(RealTime)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 40, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 220, 60, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 160, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 190, 60, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(180, 40, 60, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(180, 70, 60, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(180, 100, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(180, 130, 60, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(180, 160, 60, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(180, 190, 60, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(180, 220, 60, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(110, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        RealTime.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RealTime)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 24))
        self.menubar.setObjectName("menubar")
        RealTime.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RealTime)
        self.statusbar.setObjectName("statusbar")
        RealTime.setStatusBar(self.statusbar)

        self.retranslateUi(RealTime, city)
        QtCore.QMetaObject.connectSlotsByName(RealTime)

    def retranslateUi(self, RealTime, city: City):
        _translate = QtCore.QCoreApplication.translate
        RealTime.setWindowTitle(_translate("RealTime", city.name))
        self.label.setText(_translate("RealTime", "AQI:"))
        self.label_2.setText(_translate("RealTime", "O3:"))
        self.label_3.setText(_translate("RealTime", "CO:"))
        self.label_4.setText(_translate("RealTime", "NO2:"))
        self.label_5.setText(_translate("RealTime", "PM2.5:"))
        self.label_6.setText(_translate("RealTime", "SO2:"))
        self.label_7.setText(_translate("RealTime", "PM10:"))
        self.label_8.setText(_translate("RealTime", city.get_real_aqi()))
        self.label_9.setText(_translate("RealTime", city.get_real_o3()))
        self.label_10.setText(_translate("RealTime", city.get_real_co()))
        self.label_11.setText(_translate("RealTime", city.get_real_no2()))
        self.label_12.setText(_translate("RealTime", city.get_real_pm25()))
        self.label_13.setText(_translate("RealTime", city.get_real_so2()))
        self.label_14.setText(_translate("RealTime", city.get_real_pm10()))
        self.label_15.setText(_translate("RealTime", "Real Time"))
